services:
  postgres:
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=uzum_order_service'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
