services:
  mysql:
    image: 'mysql:8.3'
    environment:
      - 'MYSQL_DATABASE=uzum_product_service'
      - 'MYSQL_PASSWORD=mysql'
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_USER=mysql'
    ports:
      - '3306'
