server:
  port: 8761
eureka:
  instance:
    hostname: 10.10.1.170
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
